name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Decode Keystore
      env:
        ENCODED_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
        SIGNING_KEYSTORE_PATH: ${{ secrets.RELEASE_KEYSTORE_PATH }}
        ENCODED_KEYSTORE_PROPERTIES: ${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}
        ENCODED_KEYSTORE_PROPERTIES_PATH: ${{ secrets.RELEASE_KEYSTORE_PROPERTIES_PATH }}

      run: |
        echo $ENCODED_KEYSTORE > keystore-b64.txt
        base64 -d keystore-b64.txt > $SIGNING_KEYSTORE_PATH
        echo $ENCODED_KEYSTORE_PROPERTIES > keystore-properties-b64.txt
        base64 -d keystore-properties-b64.txt > $RELEASE_KEYSTORE_PROPERTIES_PATH
      
    - name: Run lint
      run: ./gradlew app:lintDebug

    - name: Build all build type and flavor permutations
      run: ./gradlew assemble
    
    - name: Run tests
      run: ./gradlew testDebug testRelease

    - name: Upload build outputs (APKs)
      uses: actions/upload-artifact@v3
      with:
        name: APKs
        path: '**/build/outputs/apk/**/*.apk'

    - name: Upload lint reports (HTML)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: lint-reports
        path: '**/build/reports/lint-results-*.html'

    - name: Upload test results (XML)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/build/test-results/test*UnitTest/**.xml'