name: PR Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  release_build:

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Cache Gradle and wrapper
      uses: actions/cache@v3
      with:
           path: |
             ~/.gradle/caches
             ~/.gradle/wrapper
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run lint
      run: ./gradlew app:lintDebug
    
    - name: Run tests
      run: ./gradlew app:testDebugUnitTest