name: Release

on:
  push:
    branches: [ "main" ]
    tags:
      - v*

jobs:
  release_build:

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Cache Gradle and wrapper
      uses: actions/cache@v3
      with:
           path: |
             ~/.gradle/caches
             ~/.gradle/wrapper
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
           
    - name: Decode Keystore
      env:
       ENCODED_STRING: ${{ secrets.RELEASE_KEYSTORE }}
       SIGNING_KEY_STORE_PATH: ${{ secrets.RELEASE_KEYSTORE_PATH }}
 
      run: |
       echo $ENCODED_STRING > keystore-b64.txt
       base64 -d keystore-b64.txt > $SIGNING_KEY_STORE_PATH

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Release apk
      run: ./gradlew assembleRelease
    
    - name: Build Release bundle
      run: ./gradlew bundleRelease
      
    - name: Upload Release Build to Artifacts
      uses: actions/upload-artifact@v3
      with:
           name: release-artifacts
           paths: |
             app/build/outputs/apk/release/
             app/build/outputs/bundle/release/
             
    - name: Create Github Release
      uses: softprops/action-gh-release@v1
      with:
           generate_release_notes: true
           prerelease: true
           files: |
             app/build/outputs/apk/release/app-release.apk
             app/build/outputs/bundle/release/app-release.aab
